// <auto-generated />
using System;
using AppAudit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAudit.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250815164332_InitEpochTime")]
    partial class InitEpochTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AppAudit.Application.Abstractions.ProgramEntry", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscoveredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresLicense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("ProgramId");

                    b.HasIndex("ProgramId")
                        .IsUnique();

                    b.ToTable("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
